name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get version info
        id: get_version
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(cat version.txt)"
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            akshaykrjain/helm-kubectl:latest
            akshaykrjain/helm-kubectl:${{ steps.get_version.outputs.sha_short }}
            akshaykrjain/helm-kubectl:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64,linux/arm64